"""
CursorCode AI - Project Builder
Generates complete project scaffolding and optionally deploys
"""

import os
import shutil
import zipfile
from datetime import datetime
from backend.ai_agents import run_agent
from backend.db_models import Projects
from backend.utils import safe_mkdir

BASE_DIR = "generated_projects"

def build_project_structure(project_name: str):
    """Creates folder structure for a project"""
    project_path = os.path.join(BASE_DIR, project_name)
    safe_mkdir(project_path)
    safe_mkdir(os.path.join(project_path, "frontend"))
    safe_mkdir(os.path.join(project_path, "backend"))
    safe_mkdir(os.path.join(project_path, "tests"))

    # Default files
    with open(os.path.join(project_path, "README.md"), "w") as f:
        f.write(f"# {project_name}\nGenerated by CursorCode AI\n")

    with open(os.path.join(project_path, ".gitignore"), "w") as f:
        f.write("venv/\n__pycache__/\nnode_modules/\n.env\n")

    return project_path

async def generate_project(api_key: str, project_name: str, prompt: str):
    """Use AI agents to generate full project code"""
    project_path = build_project_structure(project_name)

    # Generate architecture
    architecture = await run_agent(api_key, "architect", prompt)
    frontend = await run_agent(api_key, "frontend", prompt, architecture)
    backend_code = await run_agent(api_key, "backend", prompt, architecture)

    # Write frontend/backend code
    with open(os.path.join(project_path, "frontend", "app.js"), "w") as f:
        f.write(frontend)

    with open(os.path.join(project_path, "backend", "app.py"), "w") as f:
        f.write(backend_code)

    # Save project in DB
    Projects.create({
        "name": project_name,
        "prompt": prompt,
        "created_at": datetime.utcnow(),
        "path": project_path
    })

    return project_path

def zip_project(project_path: str) -> str:
    """Zip a project folder for download"""
    zip_path = f"{project_path}.zip"
    with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, _, files in os.walk(project_path):
            for file in files:
                file_path = os.path.join(root, file)
                zipf.write(file_path, os.path.relpath(file_path, project_path))
    return zip_path
