import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import Logo from "../components/Logo";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-void noise-bg">
      <header className="border-b border-white/5">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/"><Logo size="default" /></Link>
          <Link to="/" className="text-sm text-zinc-400 hover:text-white flex items-center gap-2"><ArrowLeft className="w-4 h-4" /> Back</Link>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-4 py-12">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="font-outfit font-bold text-4xl text-white mb-2">Privacy Policy</h1>
          <p className="text-zinc-500 mb-10">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>

          <div className="prose prose-invert prose-zinc max-w-none space-y-8 text-zinc-300 text-sm leading-relaxed">
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">1. Information We Collect</h2>
              <p>When you create an account, we collect your name, email address, and payment information (processed securely by Stripe). When you use our platform, we collect project data, AI-generated code, usage analytics, and technical logs.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">2. How We Use Your Information</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>To provide, maintain, and improve CursorCode AI services</li>
                <li>To process transactions and send billing notifications</li>
                <li>To personalize your experience and AI recommendations</li>
                <li>To communicate about updates, security alerts, and support</li>
                <li>To detect and prevent fraud, abuse, and security incidents</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">3. Data Storage and Security</h2>
              <p>Your data is encrypted in transit (TLS 1.3) and at rest (AES-256). We use MongoDB with authentication and access controls. Passwords are hashed with bcrypt. We conduct regular security audits and penetration testing.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">4. Code Ownership</h2>
              <p><strong className="text-white">You own all code generated by CursorCode AI.</strong> We do not claim any intellectual property rights over the output of your projects. Your code is your code.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">5. Third-Party Services</h2>
              <p>We use the following third-party services that may process your data:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li><strong className="text-white">Stripe</strong> &mdash; Payment processing (PCI DSS Level 1 compliant)</li>
                <li><strong className="text-white">xAI</strong> &mdash; AI code generation (prompts processed per their privacy policy)</li>
                <li><strong className="text-white">SendGrid</strong> &mdash; Transactional emails</li>
                <li><strong className="text-white">GitHub</strong> &mdash; OAuth authentication (optional)</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">6. Your Rights (GDPR & CCPA)</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li><strong className="text-white">Access:</strong> Request a copy of your personal data</li>
                <li><strong className="text-white">Rectification:</strong> Correct inaccurate personal data</li>
                <li><strong className="text-white">Erasure:</strong> Request deletion of your data and account</li>
                <li><strong className="text-white">Portability:</strong> Export your data in a machine-readable format</li>
                <li><strong className="text-white">Opt-out:</strong> Unsubscribe from marketing communications at any time</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">7. Cookies</h2>
              <p>We use essential cookies for authentication (JWT tokens stored in localStorage). We do not use tracking cookies or third-party analytics cookies.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">8. Data Retention</h2>
              <p>We retain your account data for as long as your account is active. Project data is retained until you delete it. Upon account deletion, all personal data is permanently removed within 30 days.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">9. Contact</h2>
              <p>For privacy-related inquiries, contact us at <a href="mailto:privacy@cursorcode.ai" className="text-electric hover:underline">privacy@cursorcode.ai</a> or use our <Link to="/contact" className="text-electric hover:underline">contact form</Link>.</p>
            </section>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
