import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft } from "lucide-react";
import Logo from "../components/Logo";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-void noise-bg">
      <header className="border-b border-white/5">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/"><Logo size="default" /></Link>
          <Link to="/" className="text-sm text-zinc-400 hover:text-white flex items-center gap-2"><ArrowLeft className="w-4 h-4" /> Back</Link>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-4 py-12">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="font-outfit font-bold text-4xl text-white mb-2">Terms of Service</h1>
          <p className="text-zinc-500 mb-10">Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</p>

          <div className="prose prose-invert prose-zinc max-w-none space-y-8 text-zinc-300 text-sm leading-relaxed">
            <section>
              <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
              <p>By accessing or using CursorCode AI ("Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
              <p>CursorCode AI is an autonomous AI software engineering platform that generates, tests, and deploys code from natural language prompts. The Service includes AI code generation, project management, deployment tools, and related features.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">3. Account Registration</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>You must provide accurate and complete information during registration</li>
                <li>You are responsible for maintaining the security of your account credentials</li>
                <li>You must be at least 18 years old or the legal age of majority in your jurisdiction</li>
                <li>One person or entity may not maintain more than one account</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">4. Intellectual Property</h2>
              <p><strong className="text-white">Your Code:</strong> You retain full ownership of all code generated through your use of CursorCode AI. You may use, modify, distribute, and commercialize generated code without restriction.</p>
              <p className="mt-2"><strong className="text-white">Our Platform:</strong> The CursorCode AI platform, including its design, features, AI models, and underlying technology, remains our intellectual property.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">5. Subscription and Billing</h2>
              <ul className="list-disc pl-5 space-y-2">
                <li>Paid plans are billed monthly via Stripe</li>
                <li>Credits reset at the beginning of each billing cycle</li>
                <li>Unused credits do not roll over to the next billing period</li>
                <li>You may upgrade, downgrade, or cancel your subscription at any time</li>
                <li>Refunds are handled on a case-by-case basis within 14 days of purchase</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">6. Acceptable Use</h2>
              <p>You agree NOT to use CursorCode AI to:</p>
              <ul className="list-disc pl-5 space-y-2">
                <li>Generate malware, viruses, or any malicious code</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe on the intellectual property rights of others</li>
                <li>Attempt to reverse-engineer the AI models or platform</li>
                <li>Abuse the credit system or circumvent usage limits</li>
                <li>Share account credentials with unauthorized users</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">7. AI-Generated Code Disclaimer</h2>
              <p>Code generated by CursorCode AI is provided "as-is." While our AI agents include security auditing, <strong className="text-white">you are responsible for reviewing, testing, and validating all generated code</strong> before deploying it to production environments.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">8. Service Availability</h2>
              <p>We strive for 99.9% uptime but do not guarantee uninterrupted service. We reserve the right to perform maintenance, which may temporarily affect availability. We are not liable for losses caused by service interruptions.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">9. Limitation of Liability</h2>
              <p>To the maximum extent permitted by law, CursorCode AI and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">10. Termination</h2>
              <p>We may suspend or terminate your account for violation of these terms. You may delete your account at any time through Settings. Upon termination, your projects and data will be permanently deleted after a 30-day grace period.</p>
            </section>

            <section>
              <h2 className="text-xl font-semibold text-white mb-3">11. Contact</h2>
              <p>Questions about these terms? Contact us at <a href="mailto:legal@cursorcode.ai" className="text-electric hover:underline">legal@cursorcode.ai</a> or use our <Link to="/contact" className="text-electric hover:underline">contact form</Link>.</p>
            </section>
          </div>
        </motion.div>
      </main>
    </div>
  );
}
